### PR TITLE
Update hash (again)

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
I think, my last PR contained an invalid hash... I am sorry!
It worked on my laptop for some reason, but not on my main PC.
Now, this one works for both of my PCs. It would be best if you try this one on yours as well to see if it is okay :)

### CODE REVIEW

**Comment by kou1okada** [comment]
O.K. I checked it again.

It seems that `pubring.asc` was updated by new one at 2022-03-05 15:56:46 GMT (= 2022-03-06 00:56:46 JST).
```
$ curl -s -D-  https://cygwin.com/key/pubring.asc
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Date: Mon, 07 Mar 2022 10:38:54 GMT
Server: Apache/2.4.37 (Red Hat Enterprise Linux) OpenSSL/1.1.1k mod_wsgi/4.6.4 Python/3.6 mod_perl/2.0.12 Perl/v5.26.3
Upgrade: h2,h2c
Connection: Upgrade
Last-Modified: Sat, 05 Mar 2022 15:56:46 GMT
ETag: "c0a-5d97aada8073b"
Accept-Ranges: bytes
Content-Length: 3082
Vary: Accept-Encoding
Content-Security-Policy: default-src 'self' http: https:
Strict-Transport-Security: max-age=16070400
Content-Type: text/plain; charset=UTF-8

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGiBEhS+m8RBAC5bn3n2yG0eqNlpg/D7DkZXQfFUBZN1D4sL/NsXKISQkA3FsiT
enDYDMFCy3NJiCDcihJprP2xs4Fc25MEcmJ4j9X93bCV4DtHv22qO1XWGkxr/XQJ
ZxYmUxFhezBOCZd+wXir0izIsGghR1+ei6i+vL4mRYy8wpMCKwf8X0qRywCg1l2J
a91PsTO6itVUACYMvKNFCHED/RenUG+kYRch9YHuDwG9LxkhgwSEZ0NIGUgZLHMY
HZDlcWBRoV6uPcqa2iKs8vvAENMcGWqo+fuRycGQ6+zlFn29IoHrcxMMM27VpifQ
91N5AqgSMPOIFkKse2VNFQ2jL4t1NfdQazRvZojwkXuYY9kB16h0Y2Zme1Pt5RgC
/wLhA/4lkttrs3ElzkAOZtrTwi7tCJnNR8/5VYnVd63NEGyAXk/qralUoQO+GNQf
ZXJUvCoYIhinHh7vzfqMT2l1gGi0FuSULX3dY5jsm0Vcu+f7XLlDoEurx1vDYCv+
9QABQDDPXuZJk55pDG1TQbvAFV8U6wWdCI5hBwcJsDfwLMzxN7QaQ3lnd2luIDxj
eWd3aW5AY3lnd2luLmNvbT6IXgQTEQIAHgUCSFL6bwIbAwYLCQgHAwIDFQIDAxYC
AQIeAQIXgAAKCRCpomL/Z2BBuncZAKCmfQS2ROcl9H8VaKmdMOB/loNRLwCfTqxf
W6L6ifl1uDwoH8t83PRjkRWIXgQTEQIAHgUCSFL6bwIbAwYLCQgHAwIDFQIDAxYC
AQIeAQIXgAAKCRCpomL/Z2BBuncZAJ98ADNWL2tWN38AiL2eOXEYp56IagCgif4P
ZVsUwfmSYs64WkwRgTcHrfq5AQ0ESFL6cBAEAIqcw0vcqdTvuukm6oiRUxkQ/jrP
+4w2FNKEK1sYG5+cbwVrf3ISTUrbTRbV3Fz5npefwaLNlIUjVYCBBWL4PuUtL4cC
rmbvMXabSYfz2qg/aqqw9xNa4G9GCdF4j9AIZaV86UHElC1wZAHTvMEdgHs8ek9k
b5rDDChUgyE+nXQ7AAMFA/4rXq6swR8m/1O8nRgNkwDvas3DbUOIdoYoFPrN7e2L
BuYWFDB+O2IUn6tAgHhDxpzO9vw58U5a/z1zm63Lf9ybHDV4c3Rqie2u2oberj1K
KStnn27KlGGvFY9kWe9WKh+ZN90/oqVGBT4+obmTiwUmVJIUy4vSZDjC0VqZHLxd
OIhJBBgRAgAJBQJIUvpwAhsMAAoJEKmiYv9nYEG6euAAniloWCmYSp4ULCHauEMb
opO2jFlwAKCwlu0FsfcO/2+AresM67hCSwxQ+pkCDQReV9H/ARAA1EPH90fI99GA
HdLMcmb75ih2F20MfNDqvrJaQ7Id0S/ot+kxB0lU0VSpdC3MjEhay/XMiASaVT5e
nNv/3+h8FYpPke0YtTz8x6rUDD3pK7gBj+xIEZwY+WbPCLJnmdPbR+ny6CKM5byI
NmbZFV52J12SH/mxWtZNgEJvxDE84/TVXSnDCyrMK2xDB4BQIQeB1NlB/NMeYFxO
ZQ7c58/t7XgxdrtEmHt5PepptPK1H6wh/Mc0styoRmVu5Bg138S+AscjtyqK1qxd
9XfIdLANLi3n7ZNEqvmDN7jvE2DZgL1/2Jr73EHMiBCJ9hsp4tU2bwiePUdBRfuE
O43he2qpSQjWheuthey9if8MtkrEWpzEObrtlQofiZWfV9NttnKd1H+s5wSX7c5J
AkSzViw3BrC/bah8qLn5X1C98Cmm3BcFV3m5LK5NTc9s8eoagkpT8c5NoD9Ez18M
/LsMqNEkDqfa9WV+ugi+BFoqrz3SOA5NWJyZOZAxyhRYFmBmY47KbbOAVsA4KYpB
43M4HCmNzxgfDkQoRAzn1wlO/q64EbmPoykuO/yAHF7Pnb8RGrvcAg5XBNVPT9kG
XMN2OHw+0fGDHhzTIRuyOd7k6yBmRleOIMn9WZUayOBCt49wBMB7j7M1rFeI6YAZ
V4tUgQslOreYA4xzUQpsb6XZ6exuqVMAEQEAAbQaQ3lnd2luIDxjeWd3aW5AY3ln
d2luLmNvbT6JAlUEEwEKAD8CGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAFiEE
VkBc9vzIFXRoKl1WGmmN6eLlYwAFAmIiqAEFCQeKmgIACgkQGmmN6eLlYwC7VQ/+
IqfecOFEqwRekRxezkyiBOpW283fY7uh7UJi14jAmiyvPJZ9gPYoHx5HNQ+ttgBZ
xrZHI8cwiRXcfk5d2KVw9AfAApFDZJNcZ4ICG3B+kRIu0WXaCagLqdB7vRkFvL/2
SyjZ9um/qL9PyEPD37hPykaGC0b5s3hTJNdSih0gFNz7/UQIsYuPaU/eM2Qgw2ZZ
wNEY+ub448g2O/Gcgj6G6tazoEe+Jmj3DNgJOp6gPuOezyT+hSXI34sop7L5/LBA
aCHEPZRFZqnIyWQdwfdgs2nZzSqE/ZLD5jAiUIh/GcJIuLEDUbzYr//1t7PwE+7l
lW/pvCTeBtefrCI12RJD91JMPSawagpB8bK607TefMKq8xtziVF+czeg91yYP0ob
sVJsYIRube382oI7eEgPlmFNa1n5Ba5jvvo4iDa1pOw1IDQvRj2FlwRsHeEFc+FG
7O6e5ULHsmP38XcWwGK8U1ruwRhy19hvUI3F+BahLRLcyyKe0UOwA7dFG9GY2YaN
w3NX84SaPjytKaF4ZU3M8RKcmHcsgVXfIKjGU03fzB2YCOexg5WjEs4kURwAZJAb
AooRRIeg6fHRvH7XL1EoEwCaa4k43tiXLVPqVyDzavy4zcnUrb3ScWwxPFR1N/aJ
B5txz6N0ySexTX5znlCXbHS2N/0xSTSePTUdP52e4weIRgQQEQoABgUCXlfTpgAK
CRCpomL/Z2BBurn6AJsEe77ARRsR1NEp06STdCbyppNJnQCggvdfcS7/HveOzENJ
u8QtWIVTThg=
=dXew
-----END PGP PUBLIC KEY BLOCK-----
```
```
$ curl -s https://cygwin.com/key/pubring.asc | sha512sum
019b3d2efe208f1441c660a34d08151b5c9675523b85e0a4ca748137ed45d086a4eb06e0efd4d86a1479246e62641a0c284ffb8c4b0b637063681a9282beca3d *-
```

I merged PR #84 at 2022-03-05 02:28 JST.
Thus, this file was updated again 22 hours after the PR closed.

I remember `pubring.asc`,  when I checked and merged PR #84,  was uploaded at 2022-03-01 maybe.
And in may memory that it was containing below key:
```
pub   rsa4096 2020-02-27 [SC] [expired: 2022-02-26]
      56405CF6FCC81574682A5D561A698DE9E2E56300
uid           [ expired] Cygwin <cygwin@cygwin.com>
```
But current 'pubring.asc` is not containting it.

I processed the PR under /tmp directory on crostini, so perhaps `pubring.asc` at that time is already lost.
I should have noted here the evidence of `pubring.asc` at the time I closed the PR.
Sorry.

**Comment by kou1okada** [comment]
The current `pubring.asc` contains below keys:
```
$ LANG=C gpg2 --with-fingerprint --list-keys
/tmp/cygwin/key/pubring.gpg
---------------------------
pub   dsa1024 2008-06-13 [SC]
      1169 DF9F 2273 4F74 3AA5  9232 A9A2 62FF 6760 41BA
uid           [ unknown] Cygwin <cygwin@cygwin.com>
sub   elg1024 2008-06-13 [E]

pub   rsa4096 2020-02-27 [SC] [expires: 2024-03-02]
      5640 5CF6 FCC8 1574 682A  5D56 1A69 8DE9 E2E5 6300
uid           [ unknown] Cygwin <cygwin@cygwin.com>
```

**Comment by ThexXTURBOXx** [comment]
Interesting, I wonder what the reason was for that key change... Thanks for the information! :)

**Comment by kou1okada** [comment]
Maybe they forgot to drop a old expired key entry from `pubring.asc`.

**Comment by kou1okada** [comment]
I compared two keys.
It seems that differences are expired date and modified time (?) only.
Those were about the key of  1A698DE9E2E56300 .
```
$ OPT_UTS=1 ./checkkey.sh pubring.asc,20220302_020007.asc
[Public keys]
/tmp/.checkkey/20220301T170007+0000/pubring.kbx
-----------------------------------------------
pub   dsa1024 2008-06-13 [SC]
      1169DF9F22734F743AA59232A9A262FF676041BA
uid           [ unknown] Cygwin <cygwin@cygwin.com>
sub   elg1024 2008-06-13 [E]

pub   rsa4096 2020-02-27 [SC] [expires: 2024-02-27]
      56405CF6FCC81574682A5D561A698DE9E2E56300
uid           [ unknown] Cygwin <cygwin@cygwin.com>

[Secret keys]
[Signatures]
/tmp/.checkkey/20220301T170007+0000/pubring.kbx
-----------------------------------------------
pub   dsa1024 2008-06-13 [SC]
      1169DF9F22734F743AA59232A9A262FF676041BA
uid           [ unknown] Cygwin <cygwin@cygwin.com>
sig!3        A9A262FF676041BA 2008-06-13  Cygwin <cygwin@cygwin.com>
sig!3        A9A262FF676041BA 2008-06-13  Cygwin <cygwin@cygwin.com>
sub   elg1024 2008-06-13 [E]
sig!         A9A262FF676041BA 2008-06-13  Cygwin <cygwin@cygwin.com>

pub   rsa4096 2020-02-27 [SC] [expires: 2024-02-27]
      56405CF6FCC81574682A5D561A698DE9E2E56300
uid           [ unknown] Cygwin <cygwin@cygwin.com>
sig!3        1A698DE9E2E56300 2022-03-01  Cygwin <cygwin@cygwin.com>
sig!         A9A262FF676041BA 2020-02-27  Cygwin <cygwin@cygwin.com>

gpg: 5 good signatures
```
```
$ OPT_UTS=1 ./checkkey.sh pubring.asc,20220306_005646.asc
[Public keys]
/tmp/.checkkey/20220305T155646+0000/pubring.kbx
-----------------------------------------------
pub   dsa1024 2008-06-13 [SC]
      1169DF9F22734F743AA59232A9A262FF676041BA
uid           [ unknown] Cygwin <cygwin@cygwin.com>
sub   elg1024 2008-06-13 [E]

pub   rsa4096 2020-02-27 [SC] [expires: 2024-03-02]
      56405CF6FCC81574682A5D561A698DE9E2E56300
uid           [ unknown] Cygwin <cygwin@cygwin.com>

[Secret keys]
[Signatures]
/tmp/.checkkey/20220305T155646+0000/pubring.kbx
-----------------------------------------------
pub   dsa1024 2008-06-13 [SC]
      1169DF9F22734F743AA59232A9A262FF676041BA
uid           [ unknown] Cygwin <cygwin@cygwin.com>
sig!3        A9A262FF676041BA 2008-06-13  Cygwin <cygwin@cygwin.com>
sig!3        A9A262FF676041BA 2008-06-13  Cygwin <cygwin@cygwin.com>
sub   elg1024 2008-06-13 [E]
sig!         A9A262FF676041BA 2008-06-13  Cygwin <cygwin@cygwin.com>

pub   rsa4096 2020-02-27 [SC] [expires: 2024-03-02]
      56405CF6FCC81574682A5D561A698DE9E2E56300
uid           [ unknown] Cygwin <cygwin@cygwin.com>
sig!3        1A698DE9E2E56300 2022-03-05  Cygwin <cygwin@cygwin.com>
sig!         A9A262FF676041BA 2020-02-27  Cygwin <cygwin@cygwin.com>

gpg: 5 good signatures
```

**Comment by kou1okada** [comment]
* [ checkkey.sh - Check key about GNUPG. ](https://gist.github.com/kou1okada/8cf7c0d556b269d9f30b7c28a89f4b55)

**Pull request merged**
