### PR TITLE
Added support for Setup.exe to use same mirror and cache dir as apt-cyg

### PR DESCRIPTION
**Pull request by FlipB**
Mirror and Cache dirs are passed with -s and -l command line switches.

This works great for me. If it doesn't work for you, check permissions on cache folder.

### CODE REVIEW

**Comment by kou1okada** [comment]
Thank you for sending a patch. 
Currently `apt-cyg` on my fork uses own settings for cache and mirror, because the original `apt-cyg` has been implimented as such way.
But I think that the best way for `apt-cyg` is to share settings of `setup.exe`.

Maybe I can take 3 choices.
1. `apt-cyg` uses own setting, that is independent from `setup.exe`. (current state)
2. `setup.exe` uses settings of `apt-cyg`. (your patch)
3. `apt-cyg` uses settings of `setup.exe`. (my suggestion)

Is the second way the best for you?
Will you cause some inconvenience, if I take the third way?

**Comment by FlipB** [comment]
Hi,

The problem I had was that it polluted my downloads folder.
I couldn't find any way to change the location of cache for the setup.exe other than the command line do that's what I went with.

Using setup.exe's settings in apt-cyg is probably better in that it reduces the risk of setup.exe failing due to insufficient permissions to the cache.

However is there any way to configure setup.exe's settings?

Regards

**Comment by kou1okada** [comment]
Settings of `setup.exe` are stored in `/etc/setup/setup.rc`.
The standard way to change the cache directory is not so difficult.
All you need to do is choose a folder on `Cygwin Setup - Select Local Package Directory` dialog of `setup.exe`. It is GUI operation.
This makes same effects with `-l` option of `setup.exe`.
And these settings will be written into `/etc/setup/setup.rc` and be permanently.
This means that is enough to change settings, you use `--use-own-conf` option only once.

Of course you can also rewrite `/etc/setup/setup.rc` with a text editor directly.

**Comment by FlipB** [comment]
I see. Having `apt-cyg` use `/etc/setup/setup.rc` would be fine then.
Are you thinking about making this the default behavior?

**Pull request merged**
