### PR TITLE
Added support for using wget to upgrade script without git

### PR DESCRIPTION
**Pull request by cslycord**
Allows for upgrading script using wget to the raw direct location of the script at github.

Obviously, if you accept the change, it would need to have the URL uncommented to use your repo's location.

Other than that, shellcheck noticed the misspelling of the THRESHOLD_OF_WARNING variable and my editor automatically removed the unneeded tabs on empty lines and the unneeded spaces on the ends of a few lines here and there.

### CODE REVIEW

**Comment by kou1okada** [comment]
Thank you for a nice  pull request.
But, I'm glad if you separate it to three of fixing a typo, rearranging spaces and upgrade-self without git.

**Comment by kou1okada** [comment]
And below URL is not good for pull request.
```
local updated_url='https://raw.githubusercontent.com/cslycord/apt-cyg/master/apt-cyg'
```

**Comment by cslycord** [comment]
Which is why I wrote that you must uncomment the line below that, which
uses the URL for the script in your repository.

**Comment by cslycord** [comment]
I can separate those into different pull requests. No worries. For what
it's worth, I wasn't aware of the spacing changes until the pull request
showed the diff, since the editor changed it automatically.

**Comment by kou1okada** [comment]
Thank you to separate a pull request to three of below:
-  Spacing #57
-  Typo #58
-  Wget #59

I'll be more happy if you drop intermediate commits each of final commits.

It can be achieved by interactive rebase with following steps:

Step 1: Start interactive rebase for last four commits.
```
git rebase -i HEAD~4
```

Step 2: Edit commit 
```
pick d1e03eb changed upgrade-self to use wget
pick 64bdcf3 make upgrade-self wget portion quiet
pick 2d1a936 Fixed self-upgrade wget to use CLI args
pick xxxxxxx bla bla bla
```
to
```
pick d1e03eb changed upgrade-self to use wget
fixup 64bdcf3 make upgrade-self wget portion quiet
fixup 2d1a936 Fixed self-upgrade wget to use CLI args
squash xxxxxxx bla bla bla
```
and save it.

Step 3: Edit commit message as
* Drop commit message &sharp;1:
* Keep commit message &sharp;4:

and save it.

**Comment by kou1okada** [comment]
It'll changes commit hash, so you should use `git push` with `-f` option.

**Comment by cslycord** [comment]
I believe the intermediate commits should be fixed now.

**Comment by cslycord** [comment]
If not, I see that pushing the changes to the commits created new branches
of "origin/name" and I'm not sure why.

**Comment by kou1okada** [comment]
Check your current working branch with:
```
git log --all --graph --color --pretty=fuller --decorate=full --summary
```
Maybe it is not "name" but "origin/name".

And your "[origin/wget](https://github.com/cslycord/apt-cyg/tree/origin/wget)" seems to be not rebased correctly.
It has typo, spacing and wget.

**Comment by cslycord** [comment]
It should be working now. I've got spacing, typo, and wget rebased.

**Comment by kou1okada** [comment]
Something wrong with your rebase.
image

I prepared three rebased branches to you.
* https://github.com/kou1okada/apt-cyg/tree/cslycord-wget-rebased 
* https://github.com/kou1okada/apt-cyg/tree/cslycord-typo-rebased
* https://github.com/kou1okada/apt-cyg/tree/cslycord-spacing-rebased

Please do `git reset --hard <above-branch>` for your branches, and then do `git push -f` each for them.

**Comment by cslycord** [comment]
Should be done.

**Comment by kou1okada** [comment]
Thank you.
That seem good.

**Pull request closed without merging**
