### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by E3V3A**
Cleanup of README by moving known forks and known problems to their own files.

### CODE REVIEW

**Comment by kou1okada** [comment]
Must I manually rewrite the table in the first section of `README.md` which has version and date when I write a new commit?
Is it a reasonable?

**Comment by E3V3A** [comment]
I agree with you to remove the maintenance badge :+1:

**Comment by E3V3A** [comment]
> Must I manually rewrite the table in the first section of `README.md` which has version and date when I write a new commit?

Unfortunately yes, as long as you don't use the `releases` github function. 
But if you just make minor non-command depending changes, I suppose it doesn't matter and need to be updated.

**Comment by E3V3A** [comment]
I suggest you just go to my patch repo and copy/edit the README yourself. I think it is just faster and easier.

**Comment by kou1okada** [comment]
Hmm,,,
Almost badges, which are written into README.md, need hardcoding the repository place to URL.
I became to think that it was not appropriate.
Because every of them must be rewritten when the repository will be forked.

Maybe it is appropriate to write outside of cloning target such as wiki instead of README.md.

**Comment by E3V3A** [comment]
Anyway, that's what I do (and most other people do as well.)
Who cares what happens when people fork it? It would just show the badge for your repo, until changed which is actually a good thing to help keep all these forks from getting even more fragmented.

**Comment by kou1okada** [comment]
Really?
Are these badges reasonable?

Looks is so good, but at least as of now I can not find other benefits about writing them into README.md.
Of course I think badges like a build state of Travis CI is very useful.
But it is better that they are related to each fork not the origin, maybe.

**Pull request merged**
